### ISSUE TITLE
Starcounter logo icon is not showing up anymore

### ISSUE THREAD

**Issue by PatrykSzwer** [Starcounter/SampleWebsiteTheme#16]
### Steps to reproduce
1. Run SignIn and login as/create acc and login as administrator.
2. Run apps: WebsiteEditor, WebsiteProvider, Images, search, SampleWebsiteTheme.
3. Go to any page, e.g http://localhost:8080/websiteeditor
### Expected result
You should see blue topbar with searchbar and starcounter logo.
### Actual result
You can see topbar with search but there is no logo anymore. Also I've tried to use logo blend URI manually (`/images/partials/somethings-single-static/qU`) somewhere else, but It's also not working. It can be even more images app issue than SampleWebsiteTheme issue.

### Screenshot
![image](https://user-images.githubusercontent.com/25042256/31815493-1f6e8eee-b58d-11e7-9295-576bd356d1bc.png)

**Comment by warpech** [comment]
Actually I don't remember seeing a Starcounter logo there at any other time than some demos. 

What was the last version that worked ok in your opinion?

PS. Regarding `/images/partials/somethings-single-static/qU`, are you sure you used a correct ID? In my video https://youtu.be/dvQHlzoN0wE?t=14m7s I am using `/images/partials/contents/{Content ID}`. Is the difference understandable?

**Comment by PatrykSzwer** [comment]
For me, when I'm running SampleWebsiteTheme, It creates DesktopSurface with blending rule:
![image](https://user-images.githubusercontent.com/25042256/31886146-6a8888ae-b7f3-11e7-96a6-e279ca6b2063.png)
Skipping that fact, that I don't have image with this ID, this proves that there is/was/should be logo in TopBarCenter blending point. Since It's not needed/used anymore I thing we should remove this rule.

**Comment by warpech** [comment]
You are right, the Logo image should be rendered according to the code in the `develop` branch of SampleWebsiteTheme but it is not.

> Also I've tried to use logo blend URI manually (/images/partials/somethings-single-static/qU) somewhere else, but It's also not working. It can be even more images app issue than SampleWebsiteTheme issue.

You can't access `/images/partials/somethings-single-static/qU` in a web browser, because Images app registers this as **SelfOnly**. You can access `/images/somethings-single-static/qU` though.

I cannot really understand why the image is not rendered.

@un-tone you are both the implementer of WebsiteProvider and the routing in the Images app. Could you please investigate this?

**Comment by un-tone** [comment]
The URI should be `/images/partials/somethings-single-static/{qU}` since the `qU` is an argument of `/images/partials/somethings-single-static/{?}` handler URI.
More info here https://docs.starcounter.io/guides/blending/blending#blending-specific-uris.

**Comment by warpech** [comment]
![image](https://user-images.githubusercontent.com/566463/32063799-6ae117bc-ba78-11e7-9891-1f9bd41e5277.png)

I completely forgot about this.

@alemoi Do you think there is some warning that we can log if a Blender.MapUri rule is unmatched?

@un-tone thanks so much for figuring this out. Could you please make a PR?

**Comment by un-tone** [comment]
Sure https://github.com/Starcounter/SampleWebsiteTheme/pull/19.

**Comment by warpech** [comment]
Setting as “Finished” because it is:
- released (with release notes) https://github.com/Starcounter/SampleWebsiteTheme/releases/tag/2.1.0
- published in the App Warehouse
