### ISSUE TITLE
Load the initial config from a SQL dump instead of a C# code

### ISSUE THREAD

**Issue by warpech** [Starcounter/SampleWebsiteTheme#3]

**Comment by andwah** [comment]
How should the user be able to create an SQL dump file if the database is not on the user's machine? (the user may be logged in to an remote site)?

**Comment by warpech** [comment]
Can the `sql` file be distributed with the package with the `exe`? Then it would work, I suppose?

**Comment by warpech** [comment]
Related: https://github.com/StarcounterAppsFreezer/Launcher/issues/222

**Comment by warpech** [comment]
The SampleWebsiteTheme should consist of:

- a `SampleWebsiteTheme.sqlite3` file created using  `StarDump.exe unload --database <current database name> --file SampleWebsiteTheme.sqlite3 --unloadtables Starcounter.HTMLComposition,Simplified.Ring6.WebContent,Simplified.Ring6.WebHttpHeader,Simplified.Ring6.WebMap,Simplified.Ring6.WebSection,Simplified.Ring6.WebTemplate,Simplified.Ring6.WebTemplateGroup,Simplified.Ring6.WebUrl,Simplified.Ring6.WebUrlProperty `
- a view (`/samplewebsitetheme`) that contains a button "Reset SampleWebsiteTheme". When this button is pressed, a modal opens with explanation "Delete the current configuration from the tables XXXX and load the  configuration from the file **SampleWebsiteTheme.sqlite3**? [OK] [Cancel]`.
   - The OK button should clean the tables and load the configuration from the file

@PatrykSzwer could you pls implement this?

**Comment by PatrykSzwer** [comment]
If I understand correctly, this button should clean everything from the involved tables and load configuration that was previously extracted as `SampleWebsiteTheme.sqlite3`. Is that right? Just want to be 100% sure.

**Comment by warpech** [comment]
Yes, I think so. Do you think that's acceptable by the user?

**Comment by PatrykSzwer** [comment]
I'm actually thinking about it. I'm not sure if we should completely wipe out every involved table. We have to ask a question to ourselves (or I have to to myself because I don't know) what is the main purpose/use case of SampleWebsiteTheme. Is it ever going to be used on filled databases? Or It's provided for fresh databases to create new environment from 0? If It's 2nd option (I imagine It's 2nd) then I think It's acceptable and even recommended.

**Comment by warpech** [comment]
Then maybe let's add an explicit checkbox in the modal?

Example:

![image](https://user-images.githubusercontent.com/566463/31955922-2d38f518-b8ea-11e7-8886-d890be7b92e2.png)

**Comment by warpech** [comment]
You might find this tip useful: https://github.com/Starcounter/StarDump/issues/68

**Comment by warpech** [comment]
I was thinking about this much and I think that a general solution will be more appreciated: https://github.com/Starcounter/Website/issues/251
